### PR TITLE
Better machine validation + allow performance presets

### LINKED ISSUE #1648: Apps v2 - (pre-5) `fly machine update` allows invalid(?) CPU/RAM combos
Playing around with changing Machine sizing. flyctl doesn't seem to do any validation of Machine scaling updates.

It's happy to let me try to update a shared-cpu-1x 256MB machine to an 8x CPU, until it gets an error from flaps:

```
$ fly m update 90800d5b346e87 --cpus 8            
...
Configuration changes to be applied to machine: 90800d5b346e87 (polished-resonance-3972)

        ... // 52 identical lines
                "guest": {
                        "cpu_kind": "shared",
-                       "cpus": 1,
+                       "cpus": 8,
                        "memory_mb": 256
                }
        }
  
? Apply changes? Yes
Updating machine 90800d5b346e87
Error could not stop machine 90800d5b346e87: failed to update VM 90800d5b346e87: invalid config.guest.memory_mb, minimum required 2048 MiB
```

I can get a shared-cpu-16x with 4096MB RAM right past `fly m update`:

```
$ fly m update 90800d5b346e87 --cpus 16 --memory 4096
```

After the update, `fly m status -d` shows
```
 ...
  "guest": {
    "cpu_kind": "shared",
    "cpus": 16,
    "memory_mb": 4096
  }
```

### PR DESCRIPTION
**Pull request by billyb2**
Should fix #1648 

This just adds some client side checks when updating machines to ensure that machines are valid. 

Relevant discussion:
https://flyio.discourse.team/t/applying-limits-to-virtual-machines-on-the-cli/1843/8

### CODE REVIEW

File: internal/command/machine/run.go [hunk 1]
```diff
@@ -588,10 +588,24 @@ func determineMachineConfig(ctx context.Context, initialMachineConf api.MachineC
...
+			var machine_type string
+
+			if strings.HasPrefix(guestSize, "shared") {
+				machine_type = "shared"
+
+			} else if strings.HasPrefix(guestSize, "performance") {
+				machine_type = "performance"
+
+			} else {
+				return machineConf, fmt.Errorf("invalid machine preset requested, '%s', expected 'shared' or 'performance'", guestSize)
```
Comment (DAlperin) [inline internal/command/machine/run.go:602]: This error is slightly misleading, we expected it to _start with_ 'shared' or 'performance' right?

File: internal/machine/update.go [hunk 2]
```diff
@@ -18,6 +18,82 @@ func Update(ctx context.Context, m *api.Machine, input *api.LaunchMachineInput)
...
+			}
+		}
+
+		if !validCpuNum {
+			return fmt.Errorf("invalid config: invalid number of CPUs for %s guest. Valid numbers are %v\nView more information here: https://fly.io/docs/about/pricing/#machines", input.Config.Guest.CPUKind, validNumCpus)
+
+		}
+
+		if input.Config.Guest.CPUKind == "shared" {
+			if input.Config.Guest.MemoryMB%256 != 0 {
```
Comment (DAlperin) [inline internal/machine/update.go:49]: Channeling jp here: these can be one if, not nested :)

File: internal/machine/update.go [hunk 3]
```diff
@@ -18,6 +18,82 @@ func Update(ctx context.Context, m *api.Machine, input *api.LaunchMachineInput)
...
+				return fmt.Errorf("invalid config: invalid memory size; must be in 256 MiB increment\nView more information here: https://fly.io/docs/about/pricing/#machines")
+
+			}
+
+		} else if input.Config.Guest.CPUKind == "performance" {
+			if input.Config.Guest.MemoryMB%1024 != 0 {
```
Comment (DAlperin) [inline internal/machine/update.go:55]: here too

**Review by DAlperin — APPROVED** [review]

File: internal/command/machine/run.go (hunk 1 above)
Comment (billyb2) [reply internal/command/machine/run.go:602]: You're right, I'll fix that now

File: internal/machine/update.go (hunk 2 above)
Comment (billyb2) [reply internal/machine/update.go]: roger roger

File: internal/machine/update.go [hunk 4]
```diff
@@ -18,6 +18,76 @@ func Update(ctx context.Context, m *api.Machine, input *api.LaunchMachineInput)
...
+			}
+		}
+
+		if !validCpuNum {
+			return fmt.Errorf("invalid config: invalid number of CPUs for %s guest. Valid numbers are %v\nView more information here: https://fly.io/docs/about/pricing/#machines", input.Config.Guest.CPUKind, validNumCpus)
+
+		}
+
+		if input.Config.Guest.CPUKind == "shared" && input.Config.Guest.MemoryMB%256 != 0 {
+			return fmt.Errorf("invalid config: invalid memory size; must be in 256 MiB increment\nView more information here: https://fly.io/docs/about/pricing/#machines")
```
Comment (tvdfly) [inline internal/machine/update.go:49]: how about adding a suggestion like:

```diff
-			return fmt.Errorf("invalid config: invalid memory size; must be in 256 MiB increment\nView more information here: https://fly.io/docs/about/pricing/#machines")
+			return fmt.Errorf("invalid config: invalid memory size %d; must be in 256 MiB increment (%d would work)\nView more information here: https://fly.io/docs/about/pricing/#machines", input.Config.Guest.MemoryMB, input.Config.Guest.MemoryMB - (input.Config.Guest.MemoryMB%256))
```

File: internal/machine/update.go [hunk 5]
```diff
@@ -18,6 +18,76 @@ func Update(ctx context.Context, m *api.Machine, input *api.LaunchMachineInput)
...
+				maxMemory = input.Config.Guest.CPUs * api.MAX_MEMORY_MB_PER_CPU
+			}
+
+			if input.Config.Guest.MemoryMB > maxMemory {
+				return fmt.Errorf("invalid config: for machines with %d CPUs, the maximum amount of memory is %d MiB\nView more information here: https://fly.io/docs/about/pricing/#machines", machinePreset.CPUs, maxMemory)
+
+			}
+
+		} else {
+			// this shouldn't happen
```
Comment (tvdfly) [inline internal/machine/update.go:85]: if getting here is a bug, reporting to sentry is a good way to ensure we see that the bug is happening.

File: internal/machine/update.go (hunk 4 above)
Comment (billyb2) [reply internal/machine/update.go:49]: That's a great idea, I'll add this in a new PR

File: internal/machine/update.go (hunk 5 above)
Comment (billyb2) [reply internal/machine/update.go:85]: Actually now that you point this out, this shouldn't ever happen, because of previous checks. I'll make a new PR that takes that into account.
