### PR TITLE
Fix pg import

### LINKED ISSUE #3309: fly pg import is broken
*Please only report specific issues with `flyctl` behavior*. Anything like a support request for your application should go to https://community.fly.io. More people watch that space and can help you faster!

**Describe the bug**
Briefly, describe what broke and provide the following details:
Running `fly pg import` on an existing PG database hosted on fly gives the informative error: `[error] failed to import database: exit status 2`.

* Operating system
Arch BTW
* `fly version`
flyctl v0.2.5 linux/amd64 Commit: 7bfd726f32a599e849a70d5c0dc4e508da78e55f BuildDate: 2024-02-15T17:33:55Z

** Paste your `fly.toml`
not applicable

** Command output: **

```text
$ fly pg create --password x --name icy-leaf-1084 --region ord --org personal --initial-cluster-size 1 --vm-size shared-cpu-1x --volume-size 1
...
$ fly pg create --password x --name cold-violet-1919 --region ord --org personal --initial-cluster-size 1 --vm-size shared-cpu-1x --volume-size 1
...
$ fly pg connect -a icy-leaf-1084
Connecting to fdaa:1:3ad4:a7b:17a:8f92:e9e8:2... complete
psql (15.3 (Debian 15.3-1.pgdg120+1))
Type "help" for help.

postgres=# create table app_name (app_name text);
CREATE TABLE
postgres=# insert into app_name values ( "cringe" );
ERROR:  column "cringe" does not exist
LINE 1: insert into app_name values ( "cringe" );
                                      ^
postgres=# insert into app_name values ( 'hi' );
INSERT 0 1
postgres=# select * from app_name;
 app_name
----------
 hi
(1 row)

postgres=# exit
$ fly pg import -a cold-violet-1919 --region ord --vm-size shared-cpu-1x postgres://postgres:x@icy-leaf-1084.flycast:5432/postgres

Created an ephemeral machine 5683990fe67108 to run the import process.
Connecting to fdaa:1:3ad4:a7b:b1ce:508b:8e69:2... complete
[info] Running pre-checks...
[info] Source Postgres version: 15.3 (Debian 15.3-1.pgdg120+1)
[info] Target Postgres version: 15.3 (Debian 15.3-1.pgdg120+1)
[info] Pre-checks completed without issue
[info] Starting import process... (This could take a while)
[error] failed to import database: exit status 2
Waiting for ephemeral machine 5683990fe67108 to be destroyed ... done.
Error: failed to run ssh: ssh shell: Process exited with status 1
```

### PR DESCRIPTION
**Pull request by billyb2**
### Change Summary

What and Why:
Relies on https://github.com/fly-apps/postgres-importer/pull/7, but basically, we just specify the machine ID of the machine to connect to when importing, rather than relying on `<appname>.internal` not resolving to the ephemeral machine.

Related to:
https://github.com/fly-apps/postgres-importer/pull/7

Fixes #3309 

---

### Documentation

- [ ] Fresh Produce
- [ ] In superfly/docs, or asked for help from docs team
- [x] n/a

### CODE REVIEW

File: internal/command/postgres/import.go [hunk 1]
```diff
@@ -95,6 +104,17 @@ func runImport(ctx context.Context) error {
...
+	machines, err := flapsClient.ListActive(ctx)
+	if err != nil {
+		return fmt.Errorf("could not retrieve machines: %w", err)
+	}
+
+	if len(machines) == 0 {
+		return fmt.Errorf("no machines are available on this app %s", appName)
+	}
+	// It doesn't matter which machine we choose
+	machineID := machines[0].ID
```
Comment (matttpt) [inline internal/command/postgres/import.go:116]: Just a thought: I think it's possible to pick the primary with [`machinesNodeRoles`](https://github.com/superfly/flyctl/blob/0bb265d6a68309fe8e65624a4e6d5f75f44ebd1d/internal/command/postgres/postgres.go#L121) or something similar.

File: internal/command/postgres/import.go [hunk 2]
```diff
@@ -82,6 +84,13 @@ func runImport(ctx context.Context) error {
 		imageRef  = flag.GetString(ctx, "image")
 	)
 
+	flapsClient, err := flapsutil.NewClientWithOptions(ctx, flaps.NewClientOpts{
+		AppName: appName,
+	})
+	if err != nil {
+		return fmt.Errorf("list of machines could not be retrieved: %w", err)
+	}
```
Comment (matttpt) [inline internal/command/postgres/import.go:92]: Since we fetch the `AppCompact` below, you could move this down and put the `AppCompact` in the [`NewClientOpts`](https://github.com/superfly/fly-go/blob/cc398257f0c97d400e9438ac9b5c7f993261bc73/flaps/flaps.go#L42-L43). This would save a round-trip to the API … if the user is connecting to the Machines API over WireGuard, so this is tiny and probably not important. But you can if you want!

**Review by matttpt — APPROVED** [review]
LGTM! Just left one small and one tiny suggestion that you can take or leave.

File: internal/command/postgres/import.go (hunk 2 above)
Comment (billyb2) [reply internal/command/postgres/import.go:92]: that's great!

File: internal/command/postgres/import.go (hunk 1 above)
Comment (billyb2) [reply internal/command/postgres/import.go:116]: oh shoot i didn't know about that! neat!

**Review by benbjohnson — APPROVED** [review]
