### PR TITLE
Run pg specific commands only on confirmed pg apps

### LINKED ISSUE #818: Listing postgres databases fails when pointing to a non-postgres Fly app
See #597 for details.

Flyctl should check if the target app is a postgres instance/cluster before trying to run this command.

### PR DESCRIPTION
**Pull request by rugwirobaker**
* `flyctl pg users list`
* `flyctl pg db list`

Fixes #818

### CODE REVIEW

File: cmd/postgres.go [hunk 1]
```diff
@@ -679,6 +679,11 @@ func runListPostgresDatabases(cmdCtx *cmdctx.CmdContext) error {
 		return fmt.Errorf("get app: %w", err)
 	}
 
+	// check if app is a postgres app
+	if app.ImageDetails.Repository != "flyio/postgres" && app.ImageDetails.Repository != "flyio/postgres-standalone" {
```
Comment (jsierles) [inline cmd/postgres.go:683]: We probably shouldn't duplicate this code, especially with hardcoded values. Can this be moved to a function?

File: docstrings/gen.go [hunk 2]
```diff
@@ -481,14 +481,14 @@ to all instances running in a specific region using the --region/-r flag.`,
 		return KeyStrings{"start <id>", "Start a Fly machine",
 			`Start a Fly machine`,
 		}
+	case "machine.status":
```
Comment (jsierles) [inline docstrings/gen.go:484]: These changes should be coming from master.

**Review by jsierles — CHANGES_REQUESTED** [review]

**Review by jsierles — APPROVED** [review]
