### PR TITLE
Set app name in context in Turboku

### LINKED ISSUE #1857: Turboku failing: Could not find App
**Describe the bug**
I'm trying to use https://fly.io/launch/heroku to migrate from Heroku to Fly.io unsuccessfully. 

**Command output:**

```text
Preparing to run: `/flyctl turboku <heroku name> <id> --org personal --region lax --name <fly.io name> --now` as root
Using heroku app: <heroku name>
Selected fly region: lax
New app created: <fly.io name>
Secrets are staged for the first deployment
Changed to new app directory  <fly.io name>
Procfile created
Dockerfile created
Wrote config file
Error Could not find App
```

The Heroku app is a simple Express.js backend.

### PR DESCRIPTION
**Pull request by matttpt**
`DeployWithConfig` requires this. I think that this should fix #1857, though I don't have a real Heroku app to test it against.

### CODE REVIEW

File: internal/command/turboku/turboku.go [hunk 1]
```diff
@@ -215,6 +215,7 @@ func run(ctx context.Context) error {
 	fmt.Fprintln(io.Out, "Dockerfile created")
 
 	appConfig.AppName = createdApp.Name
+	ctx = appconfig.WithName(ctx, appConfig.AppName)
```
Comment (dangra) [inline internal/command/turboku/turboku.go:218]: I'd add `ctx = appconfig.WithConfig(ctx, appConfig)`

and change line 186 from 
```
        appConfig := appConfig.NewConfig()
	appConfig.RawDefinition = createdApp.Config.Definition
```
to
```
     appConfig, err := appconfig.FromDefinition(&createdApp.Config.Definition)
```

This is what we are doing for `fly launch`

**Review by dangra — APPROVED** [review]
