### PR TITLE
`fly machines run`: avoid nil deref when there's no fly.toml in cwd

### LINKED ISSUE #1890: segfault in `fly m run` (maybe in dockerfile parsing?)
On master 1d93055, with the given dockerfile:
```dockerfile
FROM nginxdemos/hello:latest
RUN rm /etc/nginx/conf.d/hello.conf
ADD hello.conf /etc/nginx/conf.d/
```

Running `flyctl m run -a appsv2-test --schedule hourly .` results in a segfault.
```
❯ ~/Work/flyctl/bin/flyctl m run -a appsv2-test --schedule hourly .
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x40 pc=0x1031d4174]

goroutine 1 [running]:
github.com/superfly/flyctl/internal/appconfig.(*Config).Dockerfile(...)
	/Users/alichay/Work/flyctl/internal/appconfig/config.go:131
github.com/superfly/flyctl/internal/command/machine.determineImage({0x103934e28, 0x14000b9b410}, {0x14000b9c9e0, 0xb}, {0x16db96d4d, 0x1})
	/Users/alichay/Work/flyctl/internal/command/machine/run.go:386 +0x344
github.com/superfly/flyctl/internal/command/machine.determineMachineConfig({_, _}, {0x0, {{0x0, 0x0, 0x0}, {0x0, 0x0, 0x0}, {0x0, ...}, ...}, ...}, ...)
	/Users/alichay/Work/flyctl/internal/command/machine/run.go:764 +0xa14
github.com/superfly/flyctl/internal/command/machine.runMachineRun({0x103934e28, 0x1400070f3b0})
	/Users/alichay/Work/flyctl/internal/command/machine/run.go:261 +0x57c
github.com/superfly/flyctl/internal/command.newRunE.func1(0x140003aa500, {0x14000d8a230?, 0x5?, 0x5?})
	/Users/alichay/Work/flyctl/internal/command/command.go:110 +0x164
github.com/spf13/cobra.(*Command).execute(0x140003aa500, {0x14000d8a1e0, 0x5, 0x5})
	/Users/alichay/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:856 +0x4c0
github.com/spf13/cobra.(*Command).ExecuteC(0x14000698c80)
	/Users/alichay/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x338
github.com/spf13/cobra.(*Command).ExecuteContextC(...)
	/Users/alichay/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:911
github.com/superfly/flyctl/internal/cli.Run({0x103935aa0?, 0x140006b6f00?}, 0x14000334280, {0x14000132010, 0x7, 0x7})
	/Users/alichay/Work/flyctl/internal/cli/cli.go:36 +0x1d4
main.run()
	/Users/alichay/Work/flyctl/main.go:45 +0x12c
main.main()
	/Users/alichay/Work/flyctl/main.go:26 +0x20
```

### PR DESCRIPTION
**Pull request by alichay**
Would fix #1890 

This codifies behavior that I'm not sure is correct, necessarily.

Most examples of `fly m run` use `.` as the parameter. Sometimes, it's a docker image name instead (e.g. `registry.fly.io/xxx:yyy`).

I'm not exactly sure what's meant to happen if some other path is passed, such as `./some-dir`. In this patch, it silently ignores the path passed, and just checks to see if a path is passed at all - if so, it builds `./Dockerfile` in the cwd.

### CODE REVIEW

File: internal/command/machine/run.go [hunk 1]
```diff
@@ -383,7 +383,10 @@ func determineImage(ctx context.Context, appName string, imageOrPath string) (im
 			NoCache:    flag.GetBool(ctx, "no-build-cache"),
 		}
 
-		dockerfilePath := cfg.Dockerfile()
+		dockerfilePath := ""
+		if cfg != nil {
+			dockerfilePath = cfg.Dockerfile()
+		}
```
Comment (dangra) [inline internal/command/machine/run.go:389]: what about adding the nil check at:

https://github.com/superfly/flyctl/blob/46ba1f6164672cd3ca67819dd8b976abe68bfbd8/internal/appconfig/config.go#L131

Comment (alichay) [reply internal/command/machine/run.go:389]: `c.Build` wasn't nil there, `c` was.

Comment (alichay) [reply internal/command/machine/run.go:389]: I can if you want, but I really don't like the idea of calling methods on null objects. seems like a bad road to go down imo

Comment (dangra) [reply internal/command/machine/run.go:389]: but the Getter is buggy anyways, we have to fix it otherwise it makes any caller crash

This is common pattern I would say, protobuf generator uses it too, i.e.: [service.pb.go]( https://github.com/superfly/nomad-firecracker/blob/1e6abe700cb0f9bbf99c7d6d14ed4617882b8ebb/internal/flyd/gen/flyd/v1/service.pb.go#L236-L241)

Comment (alichay) [reply internal/command/machine/run.go:389]: Ok, guess it's the rustacean in me being a little overly defensive haha, thanks for the reference :)

Comment (dangra) [reply internal/command/machine/run.go:389]: No doubts, Go sucks in that matter.

**Review by dangra — APPROVED** [review]
How much hate if I ask for a test case? 🙉

**Comment by alichay** [comment]
> How much hate if I ask for a test case on the getters? 🙉

_oh i am absolutely **fuming** right now_

no you're totally right, tests are an easy reliability win here :)
