### PR TITLE
`scale show`: re-add --json, add json support for v2

### LINKED ISSUE #2188: fly scale show --json no longer works
**Describe the bug**
fly scale show -a app-name --json used to output json.
* Operating system
* `fly version`
flyctl v0.0.509 linux/amd64 Commit: v0.0.509 BuildDate: 1970-01-01T00:00:00Z
flyctl v0.0.544 linux/amd64 Commit: 803df3fc BuildDate: 2023-04-25T20:21:01Z
** Command output: **

```text
# on 0.0.509
{
    "Name": "shared-cpu-1x",
    "CPUCores": 1,
    "CPUClass": "",
    "MemoryGB": 0.25,
    "MemoryMB": 256,
    "PriceMonth": 1.94,
    "PriceSecond": 7.5e-7,
    "Count": "web=2 app=2 ",
    "MaxPerRegion": "app=0 web=0 worker=0 "
}

# on 0.0.544
 flyctl scale show [flags]

Flags:
  -a, --app string      Application name
  -c, --config string   Path to application configuration file
  -h, --help            help for show

Global Flags:
  -t, --access-token string   Fly API Access Token
      --verbose               verbose output

Error: unknown flag: --json
```

### PR DESCRIPTION
**Pull request by alichay**
Would fix #2188 

V2 output looks like
```
❯ ~/Work/flyctl/bin/flyctl scale show --json
[
    {
        "Process": "app",
        "Count": 2,
        "CpuKind": "shared",
        "Cpus": 1,
        "Memory": 256,
        "Regions": {
            "ord": 2
        }
    }
]
```

### CODE REVIEW

File: internal/command/scale/show_machines.go [hunk 1]
```diff
@@ -37,10 +39,56 @@ func runMachinesScaleShow(ctx context.Context) error {
...
+		}
+		return machines[0].Config.Guest
+	})
+
+	if flag.GetBool(ctx, "json") {
+		type groupData struct {
+			Process string
+			Count   int
+			CpuKind string
+			Cpus    int
```
Comment (matttpt) [inline internal/command/scale/show_machines.go:57]: This is tiny and totally optional, but I'd suggest capitalizing the acronyms, simply because it seems to match the `--json` output style for other commands.

**Review by matttpt — APPROVED** [review]
Added one little suggestion but LGTM either way!

File: internal/command/scale/show_machines.go (hunk 1 above)
Comment (rugwirobaker) [reply internal/command/scale/show_machines.go:57]: They probably need to add some json tags on those fields

Comment (dangra) [reply internal/command/scale/show_machines.go:57]: +1 to both. Go convention is to capitalize acronyms like URL, ID, HTTP, ...

**Review by dangra — APPROVED** [review]
