### PR TITLE
"Release command" machine won't get mounts, metrics, services, checks and statics 

### LINKED ISSUE #1752: fly deploy panics when mount and release command are configured
with this fly.toml:
```toml
app = "tvd-cfg-repro-2023-02-21"

[mount]
destination = "/mydata"

[deploy]
release_command = "/release_cmd.sh foo bar baz 123 --six"
```

`fly deploy` will panic with these commands:

```
% fly version
fly v0.0.463 darwin/arm64 Commit: be3d531e BuildDate: 2023-02-21T16:42:54Z

% fly apps create tvd-cfg-repro-2023-02-21
New app created: tvd-cfg-repro-2023-02-21

% fly vol create -r sea --size 1 tvd_cfg_repro_2023_02_21_vol
        ID: vol_1q85vg72yz1vzdxe
...

% curl -vs -X POST "https://api.machines.dev/v1/apps/tvd-cfg-repro-2023-02-21/machines" \
    -H "Authorization: Bearer ${FLY_API_TOKEN}" \
    -H "content-type: application/json" \
    --data-binary '{
    "region": "sea",
    "config": {
        "image": "nginx",
        "mounts": [{
            "volume": "vol_1q85vg72yz1vzdxe",
            "path": "/testdata"
        }]
    }
}'

% fly deploy --image nginx
==> Verifying app config
--> Verified app config
==> Building image
Searching for image 'nginx' remotely...
image found: img_19gm46k36kzvx0jk
WARN Found 1 machines that are not part of the Fly Apps Platform:
tvd-cfg-repro-2023-02-21 machines
ID              NAME                    STATE   REGION  IMAGE                   IP ADDRESS                      VOLUME                      CREATED                 LAST UPDATED
39080e6e2c3487  aged-glitter-9049       started sea     library/nginx:latest    fdaa:0:bfcd:a7b:f9:fb09:1c2a:2  vol_1q85vg72yz1vzdxe        2023-02-22T06:44:21Z    2023-02-22T06:44:27Z

? Migrate 1 existing machines into Fly Apps Platform? Yes
INFO Migrating 1 machines to the Fly Apps Platform
Running tvd-cfg-repro-2023-02-21 release_command: /release_cmd.sh foo bar baz 123 --six
Oops, something went wrong! Could you try that again?
```

if I run with a dev build, i get a panic.

This seems to be happening because we try to attach a volume to the release command machine and there is no volume to attach. We shouldn't attach volumes to release commands, at least for now to fix this panic.

### PR DESCRIPTION
**Pull request by dangra**
Fixes #1752 

```toml
app = "nobodyapp"

[mounts]
source = "data"
destination = "/data"

[deploy]
release_command = "echo RELEASED $(date)"
```

```console
$ fly deploy
...
image: registry.fly.io/nobodyapp:deployment-01GTHFF7XZM7DQ9QYA8Z5RW4J0
image size: 7.1 MB
Running nobodyapp release_command: echo RELEASED $(date)
  release_command 9e784e23ce0683 completed successfully
Deploying nobodyapp app with rolling strategy
  Machine 4d891ddeb67487 [app] update finished: success
  Machine 178175df95d789 [app] update finished: success
  Finished deploying
```

### CODE REVIEW

File: internal/command/deploy/machines.go [hunk 1]
```diff
@@ -563,25 +563,25 @@ func (md *machineDeployment) resolveUpdatedMachineConfig(origMachineRaw *api.Mac
...
+	if forReleaseCommand {
+		return launchInput
+	}
+
+	launchInput.Config.Metrics = md.appConfig.Metrics
+
 	if origMachineRaw.Config.Mounts != nil {
 		launchInput.Config.Mounts = origMachineRaw.Config.Mounts
-	} else if md.appConfig.Mounts != nil {
+	} else if md.appConfig.Mounts != nil && !forReleaseCommand {
```
Comment (jeregrine) [inline internal/command/deploy/machines.go:584]: you shouldn't get here cause line 577 returns.

File: internal/command/deploy/machines.go [hunk 2]
```diff
@@ -563,25 +563,25 @@ func (md *machineDeployment) resolveUpdatedMachineConfig(origMachineRaw *api.Mac
...
-		launchInput.Config.Statics = append(launchInput.Config.Statics, &api.Static{
-			GuestPath: s.GuestPath,
-			UrlPrefix: s.UrlPrefix,
-		})
-	}
-	launchInput.Config.Env = make(map[string]string)
-	for k, v := range md.appConfig.Env {
-		launchInput.Config.Env[k] = v
-	}
+	launchInput.Config.Guest = origMachineRaw.Config.Guest
```
Comment (jeregrine) [inline internal/command/deploy/machines.go:567]: you lost the nil check here https://github.com/superfly/flyctl/pull/1810/files#diff-4251d8215f73cf413b3febd989c9853c5c6d80d94c5b8ced61697ff05c8e563fL596 unclear if its necessary but its maybe its a chesterson's fence thing.

File: internal/command/deploy/machines.go (hunk 1 above)
Comment (dangra) [reply internal/command/deploy/machines.go:584]: true!

File: internal/command/deploy/machines.go (hunk 2 above)
Comment (dangra) [reply internal/command/deploy/machines.go:567]: you are right, my line of thoughts is that `launchInput.Config.Guest` is nil already so overriding it by `origMachineRaw.Config.Guest` in case the later is nil is the same outcome.

File: internal/command/deploy/machines.go (hunk 1 above)
Comment (dangra) [reply internal/command/deploy/machines.go]: removed by 30f80df7

**Review by billyb2 — APPROVED** [review]
not entirely sure about everything but 👍🏾
